### ISSUE TITLE
Use Processing.js v1.4.8.

### ISSUE THREAD

**Issue by aengelke** [fjenett/javascript-mode-processing#17]

**Comment by teo1978** [comment]
Or even better https://github.com/fjenett/javascript-mode-processing/issues/20

**Comment by GoToLoop** [comment]
@teo1978 version 1.4.12 doesn't seem a stand-alone JS file! It doesn't work for JS Mode!

**Comment by teo1978** [comment]
What do you mean it is not a standalone js file??

**Comment by fjenett** [comment]
Ech. Almost a year since i wrote that comment above … So sorry.

**Comment by teo1978** [comment]
@GoToLoop I just tried replacing processing.js version 1.4.12 into the "template" folder of JavaScript mode, and I tried to export some random sketch and it works for me. I haven't tested any further than that, but could you elaborate a bit about what you mean when you say "It doesn't work for JS Mode"?

I did see a glitch, which is the output of print/println has broken style which makes it unreadable (light-gray text on slightly-less-light-gray background) but I don't know whether that's a bug in processing.js or in the html template in JavaScript mode.

**Comment by GoToLoop** [comment]
Sorry! From the link @Pomax passed to us, I've failed to spot the right "processing.js" file and taken from /scr/ subfolder. It was supposed to be from the root! @_@
But since he locked up the discussion there, I can't correct myself anymore!  =(
Pasted root's "processing.js" in JS Mode's "/template/" subfolder and my example run and even Processing.instances started to work too!
